package cardproduct

// CardProduct represent the infos from a Network.
type CardProduct struct {
	Network     string
	Code        string
	Descirption string
}

// GetInfo is returning from the given code the infos on the card.
// This will send a nil CardoProduct if not found.
func GetInfo(code string) *CardProduct {
	for k := range cardProductList {
		if cardProductList[k].Code == code {
			return &CardProduct{
				Network:     cardProductList[k].Network,
				Code:        cardProductList[k].Code,
				Descirption: cardProductList[k].Descirption,
			}
		}
	}
	// not found.
	return nil
}

var cardProductList = []CardProduct{
	{"CB", "1", "Carte nationale de retrait"},
	{"CB", "2", "Carte nationale de retrait et de paiement"},
	{"CB", "3", "Carte nationale de paiement"},
	{"CB", "4", "Carte nationale de paiement et de retrait a autorisation systematique"},
	{"CB", "5", "Carte nationale de paiement a autorisation systematique"},
	{"CB", "XX", "CB"},
	{"MASTERCARD", "CIR", "CIR - CIRRUS"},
	{"MASTERCARD", "DDB", "DDB - DOMESTIC DEBIT BRAND"},
	{"MASTERCARD", "DLG", "DLG - DEBIT GOLD DELAYED DEBIT"},
	{"MASTERCARD", "DLH", "DLH - DEBIT WORLD EMBOSSED DELAYED DEBIT"},
	{"MASTERCARD", "DLP", "DLP - DEBIT PLATINUM DELAYED DEBIT"},
	{"MASTERCARD", "DLS", "DLS - DEBIT MASTERCARD CARD DELAYED DEBIT"},
	{"MASTERCARD", "ECH", "ECH - EUROCHEQUE PICTOGRAM"},
	{"MASTERCARD", "MAB", "MAB - WORLD ELITE MASTERCARD"},
	{"MASTERCARD", "MAC", "MAC - MASTERCARD CORPORATE WORLD ELITE"},
	{"MASTERCARD", "MBD", "MasterCard Professional Debit BusinessCard Card"},
	{"MASTERCARD", "MBE", "MBE - MASTERCARD ELECTRONIC BUSINESS CARD"},
	{"MASTERCARD", "MBK", "MBK - MASTERCARD BLACK"},
	{"MASTERCARD", "MCB", "MCB - MASTERCARD BUSINESS CARD"},
	{"MASTERCARD", "MCC", "MCC - MASTERCARD CREDIT (MIXED BIN) CARD"},
	{"MASTERCARD", "MCD", "MCD - MASTERCARD DEBIT CARD"},
	{"MASTERCARD", "MCE", "MCE - MASTERCARD ELECTRONIC CARD"},
	{"MASTERCARD", "MCF", "MCF - MASTERCARD FLEET CARD"},
	{"MASTERCARD", "MCG", "MCG - MASTERCARD GOLD CARD"},
	{"MASTERCARD", "MCH", "MCH - MasterCard Premium Charge"},
	{"MASTERCARD", "MCO", "MCO - MASTERCARD CORPORATE CARD"},
	{"MASTERCARD", "MCP", "MCP - MASTERCARD PURCHASING CARD"},
	{"MASTERCARD", "MCS", "MCS - MASTERCARD STANDARD CARD"},
	{"MASTERCARD", "MCT", "MCT - MasterCard Titanium"},
	{"MASTERCARD", "MCV", "MCV - MERCHANT BRANDED PROGRAM"},
	{"MASTERCARD", "MCW", "MCW - WORLD MASTERCARD CARD"},
	{"MASTERCARD", "MDB", "Debit MasterCard BusinessCard Card"},
	{"MASTERCARD", "MDG", "MDG - DEBIT GOLD MASTERCARD CARD"},
	{"MASTERCARD", "MDH", "MDH - WORLD DEBIT EMBOSSED"},
	{"MASTERCARD", "MDJ", "MDJ - DEBIT OTHER 2 EMBOSSED"},
	{"MASTERCARD", "MDL", "MDL - DEBIT BUSINESS CARD STANDARD"},
	{"MASTERCARD", "MDN", "MDN - BUSINESS DEBIT OTHER 2 EMBOSSED"},
	{"MASTERCARD", "MDO", "MDO - DEBIT OTHER CARD"},
	{"MASTERCARD", "MDP", "MDP - DEBIT PLATINUM CARD"},
	{"MASTERCARD", "MDR", "MDR - DEBIT BROKERAGE CARD"},
	{"MASTERCARD", "MDS", "MDS - DEBIT MASTERCARD CARD"},
	{"MASTERCARD", "MDT", "MDT - COMMERCIAL DEBIT MASTERCARD CARD"},
	{"MASTERCARD", "MEC", "MEC - MASTERCARD ELECTRONIC COMMERCIAL CARD"},
	{"MASTERCARD", "MEF", "MEF - ELECTRONIC PAYMENT ACCOUNT"},
	{"MASTERCARD", "MFB", "MFB - Flex World Elite"},
	{"MASTERCARD", "MFD", "MFD - Flex Platinum"},
	{"MASTERCARD", "MFE", "MFE - Flex Charge World Elite"},
	{"MASTERCARD", "MFH", "MFH - Flex World"},
	{"MASTERCARD", "MFL", "MFL - Flex Charge Platinum"},
	{"MASTERCARD", "MFW", "MFW - Flex Charge World"},
	{"MASTERCARD", "MGF", "MGF - MASTERCARD GOUVERNMENT COMMERCIAL CARD"},
	{"MASTERCARD", "MHA", "MasterCard Healthcare Prepaid Non-Tax"},
	{"MASTERCARD", "MIA", "Prepaid MasterCard Unembossed Student Card"},
	{"MASTERCARD", "MIP", "Prepaid Debit MasterCard Student Card"},
	{"MASTERCARD", "MIU", "Debit MasterCard Unembossed (Non-U.S.)"},
	{"MASTERCARD", "MNF", "MNF - MASTERCARD PUBLIC SECTOR COMMERCIAL CARD"},
	{"MASTERCARD", "MNW", "MNW - MASTERCARD NEW WORLD"},
	{"MASTERCARD", "MOG", "MOG - MAESTRO GOLD"},
	{"MASTERCARD", "MOP", "MOP - MAESTRO PLATINIUM"},
	{"MASTERCARD", "MOW", "MOW - MAESTRO WORLD"},
	{"MASTERCARD", "MPA", "MasterCard Prepaid Debit Standard ? Payroll"},
	{"MASTERCARD", "MPB", "MPB - PREFERRED BUSINESS CARD"},
	{"MASTERCARD", "MPF", "MasterCard Prepaid Debit Standard ? Gift"},
	{"MASTERCARD", "MPG", "MPG - MASTERCARD UNEMBOSSED PREPAID STUDENT CARD"},
	{"MASTERCARD", "MPJ", "MPJ - PREPAID DEBIT MASTERCARD CARD GOLD"},
	{"MASTERCARD", "MPK", "MPK - PREPAID MASTERCARD GOUVERNMENT COMMERCIAL CARD"},
	{"MASTERCARD", "MPL", "MPL - PLATINIUM MASTERCARD CARD"},
	{"MASTERCARD", "MPM", "MasterCard Prepaid Debit Standard ? Consumer Incentive"},
	{"MASTERCARD", "MPN", "MasterCard Prepaid Debit Standard ? Insurance"},
	{"MASTERCARD", "MPO", "MasterCard Prepaid Debit Standard ? Other"},
	{"MASTERCARD", "MPP", "MPP - PRE-PAID CARD"},
	{"MASTERCARD", "MPR", "MasterCard Prepaid Debit Standard ? Travel"},
	{"MASTERCARD", "MPT", "MasterCard Prepaid Debit Standard ? Teen"},
	{"MASTERCARD", "MPV", "MasterCard Prepaid Debit Standard ? Government"},
	{"MASTERCARD", "MPW", "Debit MasterCard BusinessCard Prepaid Workplace Business to Business"},
	{"MASTERCARD", "MPX", "MasterCard Prepaid Debit Standard ? Flex Benefit"},
	{"MASTERCARD", "MPY", "MasterCard Prepaid Debit Standard ? Employee Incentive"},
	{"MASTERCARD", "MPZ", "MasterCard Prepaid Debit Standard ? Government Consumer"},
	{"MASTERCARD", "MRC", "MRC - MASTERCARD ELECTRONIC CONSUMER PREPAID"},
	{"MASTERCARD", "MRF", "Standard Deferred"},
	{"MASTERCARD", "MRG", "MRG - MASTERCARD STANDARD PREPAID"},
	{"MASTERCARD", "MRH", "MasterCard Platinum Prepaid Travel"},
	{"MASTERCARD", "MRJ", "MRJ - PREPAID MASTERCARD GOLD CARD"},
	{"MASTERCARD", "MRK", "MRK - PREPAID MASTERCARD PUBLIC SECTOR COMMERCIAL CARD"},
	{"MASTERCARD", "MRO", "MRO - MasterCard Rewards Only"},
	{"MASTERCARD", "MRP", "Standard Retailer Centric Payments"},
	{"MASTERCARD", "MRW", "MRW - MASTERCARD CREDIT BUSINESS CARD PREPAID"},
	{"MASTERCARD", "MSA", "MSA - PREPAID MAESTRO PAYROLL CARD"},
	{"MASTERCARD", "MSB", "MSB - MAESTRO SMALL BUSINESS"},
	{"MASTERCARD", "MSF", "MSF - PREPAID MAESTRO GIFT CARD"},
	{"MASTERCARD", "MSG", "MSG - PREPAID MAESTRO CONSUMER RELOADABLE CARD"},
	{"MASTERCARD", "MSI", "MSI - MAESTRO"},
	{"MASTERCARD", "MSJ", "MSJ - PREPAID MAESTRO GOLD"},
	{"MASTERCARD", "MSM", "MSM - PREPAID MAESTRO CONSUMER PROMOTION CARD"},
	{"MASTERCARD", "MSN", "MSN - PREPAID MAESTRO INSURANCE CARD"},
	{"MASTERCARD", "MSO", "MSO - PREPAID MAESTRO OTHER CARD"},
	{"MASTERCARD", "MSQ", "MSQ - RESERVED FOR FUTURE USE"},
	{"MASTERCARD", "MSR", "MSR - PREPAID MAESTRO TRAVEL CARD"},
	{"MASTERCARD", "MST", "MST - PREPAID MAESTRO TEEN CARD"},
	{"MASTERCARD", "MSV", "MSV - PREPAID MAESTRO GOVERNMENT BENEFIT CARD"},
	{"MASTERCARD", "MSW", "MSW - PREPAID MAESTRO CORPORATE CARD"},
	{"MASTERCARD", "MSX", "MSX - PREPAID MAESTRO FLEX BENEFIT CARD"},
	{"MASTERCARD", "MSY", "MSY - PREPAID MAESTRO EMPLOYEE INSENTIVE CARD"},
	{"MASTERCARD", "MSZ", "MSZ - PREPAID MAESTRO EMERGENCY ASSISTANCE CARD"},
	{"MASTERCARD", "MUW", "MUW - World Domestic Affluent"},
	{"MASTERCARD", "MWB", "MWB - WORLD MASTERCARD FOR BUSINESS"},
	{"MASTERCARD", "MWD", "World Deferred"},
	{"MASTERCARD", "MWE", "MWE - MASTERCARD WORLD ELITE"},
	{"MASTERCARD", "MWO", "MWO - MASTERCARD CORPORATE WORLD"},
	{"MASTERCARD", "MWR", "World Retailer Centric Payments"},
	{"MASTERCARD", "OLB", "OLB - MAESTRO SMALL BUSINESS DELAYED DEBIT"},
	{"MASTERCARD", "OLG", "OLG - MAESTRO GOLD DELAYED DEBIT"},
	{"MASTERCARD", "OLP", "OLP - MAESTRO PLATINUM DELAYED DEBIT"},
	{"MASTERCARD", "OLS", "OLS - MAESTRO DELAYED DEBIT"},
	{"MASTERCARD", "OLW", "OLW - MAESTRO WORLD DELAYED DEBIT"},
	{"MASTERCARD", "PRO", "PRO - PROPRIETARY"},
	{"MASTERCARD", "PVA", "PVA - PRIVATE LABEL A"},
	{"MASTERCARD", "PVB", "PVB - PRIVATE LABEL B"},
	{"MASTERCARD", "PVC", "PVC - PRIVATE LABEL C"},
	{"MASTERCARD", "PVD", "PVD - PRIVATE LABEL D"},
	{"MASTERCARD", "PVE", "PVE - PRIVATE LABEL E"},
	{"MASTERCARD", "PVF", "PVF - PRIVATE LABEL F"},
	{"MASTERCARD", "PVG", "PVG - PRIVATE LABEL G"},
	{"MASTERCARD", "PVH", "PVH - PRIVATE LABEL H"},
	{"MASTERCARD", "PVI", "PVI - PRIVATE LABEL I"},
	{"MASTERCARD", "PVJ", "PVJ - PRIVATE LABEL J"},
	{"MASTERCARD", "PVL", "PVL - PRIVATE LABEL CARD"},
	{"MASTERCARD", "TBE", "TBE - MASTERCARD ELECTRONIC BUSINESS IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCB", "TCB - MASTERCARD BUSINESS CARD IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCC", "TCC - MASTERCARD CREDIT (MIXED BIN) IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCE", "TCE - MASTERCARD ELECTRONIC IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCF", "TCF - MASTERCARD FLEET CARD IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCG", "TCG - MASTERCARD GOLD CARD IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCO", "TCO - MASTERCARD CORPORATE IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCP", "TCP - MASTERCARD PURCHASING CARD IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCS", "TCS - MASTERCARD STANDARD CARD IMMEDIATE DEBIT"},
	{"MASTERCARD", "TCW", "TCW - WORLD SIGNIA MASTERCARD CARD IMMEDIATE DEBIT"},
	{"MASTERCARD", "TEC", "TEC - MASTERCARD ELECTRONIC COMMERCIAL IMMEDIATE DEBIT"},
	{"MASTERCARD", "TNF", "TNF - MASTERCARD PUBLIC SECTOR COMMERCIAL CARD IMMEDIATE DE"},
	{"MASTERCARD", "TNW", "TNW - MASTERCARD NEW WORLD IMMEDIATE DEBIT"},
	{"MASTERCARD", "TPB", "TPB - PREFERRED BUSINESS CARD IMMEDIATE DEBIT"},
	{"MASTERCARD", "TPL", "TPL - PLATINUM MASTERCARD IMMEDIATE DEBIT"},
	{"MASTERCARD", "ZZ", "MASTERCARD"},
	{"VISA", "A", "Visa Traditional"},
	{"VISA", "AX", "American Express"},
	{"VISA", "B", "Visa Traditional Rewards"},
	{"VISA", "C", "Visa Signature"},
	{"VISA", "D", "Visa Signature Preferred"},
	{"VISA", "DI", "Discover"},
	{"VISA", "DN", "Diners"},
	{"VISA", "E", "Proprietary ATM"},
	{"VISA", "F", "Visa Classic"},
	{"VISA", "G", "Visa Business"},
	{"VISA", "G1", "Visa Signature Business"},
	{"VISA", "G2", "Reserved"},
	{"VISA", "G3", "Visa Business Enhanced (U.S. only)"},
	{"VISA", "H", "Reserved"},
	{"VISA", "I", "Visa Infinite"},
	{"VISA", "J", "Reserved"},
	{"VISA", "J1", "Reserved"},
	{"VISA", "J2", "Reserved"},
	{"VISA", "J3", "Visa Healthcare"},
	{"VISA", "J4", "Reserved"},
	{"VISA", "JC", "JCB"},
	{"VISA", "K", "Visa Corporate T&E"},
	{"VISA", "K1", "Visa GSA Corporate T&E"},
	{"VISA", "L", "Electron"},
	{"VISA", "M", "MasterCard"},
	{"VISA", "N", "Visa Platinum"},
	{"VISA", "N1", "Visa Rewards"},
	{"VISA", "P", "Visa Gold"},
	{"VISA", "Q", "Private Label"},
	{"VISA", "Q1", "Reserved"},
	{"VISA", "R", "Proprietary"},
	{"VISA", "S", "Visa Purchasing"},
	{"VISA", "S1", "Visa Purchasing with Fleet"},
	{"VISA", "S2", "Visa GSA Purchasing"},
	{"VISA", "S3", "Visa GSA Purchasing with Fleet"},
	{"VISA", "S4", "Government Services Loan"},
	{"VISA", "S5", "Commercial Transport EBT"},
	{"VISA", "S6", "Business Loan"},
	{"VISA", "S7", "Visa Distribution"},
	{"VISA", "T", "Reserved"},
	{"VISA", "U", "Visa Travel Money"},
	{"VISA", "V", "V PAY"},
	{"VISA", "W", "Reserved"},
	{"VISA", "X", "Reserved"},
	{"VISA", "Y", "Reserved"},
	{"VISA", "YY", "VISA"},
	{"VISA", "Z", "Reserved"},
}
